name: Build jxrlib with MSVC

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build jxrlib (MSVC NMAKE)
        run: |
          nmake /f Makefile.mak all

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: jxrlib-windows-build
          path: |
            bin/*.exe
            bin/*.dll
            bin/*.lib
